/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

/**
 *
 * @author Emanuel Baciu
 */
public class Interface1 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interface1.class.getName());

    /**
     * Creates new form Interface1
     */
    public Interface1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_MAIN_STREET = new javax.swing.JTextField();
        jTextField_BYERS = new javax.swing.JTextField();
        jTextField_WSQK = new javax.swing.JTextField();
        jTextField_BLOODCOUNT = new javax.swing.JTextField();
        jLabel_MAIN_STREET = new javax.swing.JLabel();
        jLabel_BAYERS = new javax.swing.JLabel();
        jLabel_WSQK = new javax.swing.JLabel();
        jLabel_BLOOD = new javax.swing.JLabel();
        jTextField_PORTAL1_ENTER = new javax.swing.JTextField();
        jTextField_PORTAL2_ENTER = new javax.swing.JTextField();
        jTextField_PORTAL3_ENTER = new javax.swing.JTextField();
        jTextField_PORTAL4_ENTER = new javax.swing.JTextField();
        jTextField_PORTAL1_EXIT = new javax.swing.JTextField();
        jTextField_PORTAL2_EXIT = new javax.swing.JTextField();
        jTextField_PORTAL3_EXIT = new javax.swing.JTextField();
        jTextField_PORTAL4_EXIT = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jTextField_FOREST_CHILDREN = new javax.swing.JTextField();
        jTextField_FOREST_DEMOS = new javax.swing.JTextField();
        jTextField_LAB_CHILDREN = new javax.swing.JTextField();
        jTextField_LAB_DEMOS = new javax.swing.JTextField();
        jTextField_MALL_CHILDREN = new javax.swing.JTextField();
        jTextField_MALL_DEMOS = new javax.swing.JTextField();
        jTextField_SEWER_CHILDREN = new javax.swing.JTextField();
        jTextField_SEWER_DEMOS = new javax.swing.JTextField();
        jTextField_HIVE_CAPTURED = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel_FOREST = new javax.swing.JLabel();
        jLabel_LABORATORY = new javax.swing.JLabel();
        jLabel_MALL = new javax.swing.JLabel();
        jLabel_SEWERS = new javax.swing.JLabel();
        jLabel_UNSAFE_ZONES = new javax.swing.JLabel();
        jLabel_PORTALS = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Epsteins vs Children");

        jTextField_MAIN_STREET.setText("jTextField1");
        jTextField_MAIN_STREET.addActionListener(this::jTextField_MAIN_STREETActionPerformed);

        jTextField_BYERS.setText("jTextField1");

        jTextField_WSQK.setText("jTextField1");

        jTextField_BLOODCOUNT.setText("jTextField2");

        jLabel_MAIN_STREET.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_MAIN_STREET.setText("MAIN STREET");

        jLabel_BAYERS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_BAYERS.setText("BYERS BASEMENT");

        jLabel_WSQK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_WSQK.setText("RADIO WSQK");

        jLabel_BLOOD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_BLOOD.setText("BLOOD");

        jTextField_PORTAL1_ENTER.setText("jTextField1");

        jTextField_PORTAL2_ENTER.setText("jTextField1");

        jTextField_PORTAL3_ENTER.setText("jTextField1");
        jTextField_PORTAL3_ENTER.addActionListener(this::jTextField_PORTAL3_ENTERActionPerformed);

        jTextField_PORTAL4_ENTER.setText("jTextField1");

        jTextField_PORTAL1_EXIT.setText("jTextField1");

        jTextField_PORTAL2_EXIT.setText("jTextField1");

        jTextField_PORTAL3_EXIT.setText("jTextField1");

        jTextField_PORTAL4_EXIT.setText("jTextField1");

        jTextField_FOREST_CHILDREN.setText("jTextField2");

        jTextField_FOREST_DEMOS.setText("jTextField3");

        jTextField_LAB_CHILDREN.setText("jTextField4");

        jTextField_LAB_DEMOS.setText("jTextField5");

        jTextField_MALL_CHILDREN.setText("jTextField6");

        jTextField_MALL_DEMOS.setText("jTextField7");

        jTextField_SEWER_CHILDREN.setText("jTextField8");

        jTextField_SEWER_DEMOS.setText("jTextField9");

        jTextField_HIVE_CAPTURED.setText("jTextField2");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HIVE CHILDREN");

        jLabel_FOREST.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_FOREST.setText("FOREST");

        jLabel_LABORATORY.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_LABORATORY.setText("LABORATORY");

        jLabel_MALL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_MALL.setText("MALL");

        jLabel_SEWERS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_SEWERS.setText("SEWERS");

        jLabel_UNSAFE_ZONES.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_UNSAFE_ZONES.setText("UPSIDEDOWN");
        jLabel_UNSAFE_ZONES.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel_PORTALS.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_PORTALS.setText("PORTALS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel_MAIN_STREET, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(jLabel_BAYERS, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_BYERS)
                                    .addComponent(jTextField_MAIN_STREET)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField_WSQK, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(31, 31, 31)
                                                .addComponent(jLabel_WSQK, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField_BLOODCOUNT, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                            .addComponent(jLabel_BLOOD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(jLabel_PORTALS, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_PORTAL1_ENTER, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(jTextField_PORTAL2_ENTER)
                            .addComponent(jTextField_PORTAL3_ENTER)
                            .addComponent(jTextField_PORTAL4_ENTER))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(jSeparator3)
                            .addComponent(jSeparator4)
                            .addComponent(jSeparator1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField_PORTAL1_EXIT)
                                .addComponent(jTextField_PORTAL2_EXIT)
                                .addComponent(jTextField_PORTAL3_EXIT, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField_PORTAL4_EXIT, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(jLabel_UNSAFE_ZONES, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField_FOREST_CHILDREN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_LAB_CHILDREN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_MALL_CHILDREN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_SEWER_CHILDREN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(36, 36, 36)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField_SEWER_DEMOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_MALL_DEMOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_LAB_DEMOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jTextField_FOREST_DEMOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTextField_HIVE_CAPTURED, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(jLabel_FOREST, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(232, 232, 232))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel_LABORATORY, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel_MALL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel_SEWERS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(317, 317, 317)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_MAIN_STREET)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField_PORTAL1_EXIT, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(jTextField_PORTAL2_EXIT, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(jTextField_PORTAL3_EXIT, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(jTextField_PORTAL4_EXIT, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField_MAIN_STREET, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField_PORTAL1_ENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel_BAYERS)
                                            .addComponent(jTextField_PORTAL2_ENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextField_BYERS, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(33, 33, 33)
                                                .addComponent(jTextField_PORTAL3_ENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel_WSQK)
                                            .addComponent(jLabel_BLOOD))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField_WSQK)
                                            .addComponent(jTextField_PORTAL4_ENTER)
                                            .addComponent(jTextField_BLOODCOUNT)))
                                    .addComponent(jLabel_PORTALS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(162, 162, 162))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_UNSAFE_ZONES, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(132, 132, 132)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(134, 134, 134)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(136, 136, 136)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel_FOREST)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField_FOREST_DEMOS)
                                        .addComponent(jTextField_FOREST_CHILDREN, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextField_HIVE_CAPTURED, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addComponent(jLabel_LABORATORY)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_LAB_DEMOS)
                                    .addComponent(jTextField_LAB_CHILDREN, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addComponent(jLabel_MALL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_MALL_CHILDREN)
                                    .addComponent(jTextField_MALL_DEMOS, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addComponent(jLabel_SEWERS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_SEWER_CHILDREN)
                                    .addComponent(jTextField_SEWER_DEMOS, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_MAIN_STREETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_MAIN_STREETActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_MAIN_STREETActionPerformed

    private void jTextField_PORTAL3_ENTERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PORTAL3_ENTERActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PORTAL3_ENTERActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interface1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_BAYERS;
    private javax.swing.JLabel jLabel_BLOOD;
    private javax.swing.JLabel jLabel_FOREST;
    private javax.swing.JLabel jLabel_LABORATORY;
    private javax.swing.JLabel jLabel_MAIN_STREET;
    private javax.swing.JLabel jLabel_MALL;
    private javax.swing.JLabel jLabel_PORTALS;
    private javax.swing.JLabel jLabel_SEWERS;
    private javax.swing.JLabel jLabel_UNSAFE_ZONES;
    private javax.swing.JLabel jLabel_WSQK;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField_BLOODCOUNT;
    private javax.swing.JTextField jTextField_BYERS;
    private javax.swing.JTextField jTextField_FOREST_CHILDREN;
    private javax.swing.JTextField jTextField_FOREST_DEMOS;
    private javax.swing.JTextField jTextField_HIVE_CAPTURED;
    private javax.swing.JTextField jTextField_LAB_CHILDREN;
    private javax.swing.JTextField jTextField_LAB_DEMOS;
    private javax.swing.JTextField jTextField_MAIN_STREET;
    private javax.swing.JTextField jTextField_MALL_CHILDREN;
    private javax.swing.JTextField jTextField_MALL_DEMOS;
    private javax.swing.JTextField jTextField_PORTAL1_ENTER;
    private javax.swing.JTextField jTextField_PORTAL1_EXIT;
    private javax.swing.JTextField jTextField_PORTAL2_ENTER;
    private javax.swing.JTextField jTextField_PORTAL2_EXIT;
    private javax.swing.JTextField jTextField_PORTAL3_ENTER;
    private javax.swing.JTextField jTextField_PORTAL3_EXIT;
    private javax.swing.JTextField jTextField_PORTAL4_ENTER;
    private javax.swing.JTextField jTextField_PORTAL4_EXIT;
    private javax.swing.JTextField jTextField_SEWER_CHILDREN;
    private javax.swing.JTextField jTextField_SEWER_DEMOS;
    private javax.swing.JTextField jTextField_WSQK;
    // End of variables declaration//GEN-END:variables
}
